apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-deployment
  namespace: netology-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c"]
        args:
        - while true; do echo "Hello from Busybox" >> /shared/data.txt; sleep 5; done
        volumeMounts:
        - name: shared-data
          mountPath: /shared
      - name: multitool
        image: praqma/network-multitool
        command: ["sh", "-c"]
        args:
        - while true; do cat /shared/data.txt; sleep 5; done
        volumeMounts:
        - name: shared-data
          mountPath: /shared
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: local-pvc
