apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  namespace: netology-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 158.160.1.229                     # IP NFS-сервера
  share: /var/snap/microk8s/common/nfs-storage             # Путь к общему каталогу
