apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: netology-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: local-pv
